-- Supabase SQL: شغّل هذا في SQL Editor
create table if not exists public.drivers (
 id bigint generated by default as identity primary key,
 name text not null,
 status text not null default 'available' check(status in ('available','out')),
 priority integer not null default 1,
 created_at timestamptz not null default now()
);

create table if not exists public.delivery_orders (
 id bigint generated by default as identity primary key,
 driver_id bigint references public.drivers(id) on delete cascade,
 driver_name text not null,
 order_number text not null,
 status text not null default 'out' check(status in ('out','returned')),
 departed_at timestamptz not null default now(),
 returned_at timestamptz,
 created_at timestamptz not null default now()
);

insert into public.drivers(name,priority)
select * from (values
('شاهد',1),('نعيم',2),('ارشد',3),('صمد',4),('منور علي',5),
('شهزاد',6),('Anam',7),('Naeem UD',8),('اديب',9)
) v(name,priority)
where not exists (select 1 from public.drivers);

alter table public.drivers enable row level security;
alter table public.delivery_orders enable row level security;

create policy "public read drivers" on public.drivers for select using (true);
create policy "public insert drivers" on public.drivers for insert with check (true);
create policy "public update drivers" on public.drivers for update using (true) with check (true);
create policy "public delete drivers" on public.drivers for delete using (true);

create policy "public read orders" on public.delivery_orders for select using (true);
create policy "public insert orders" on public.delivery_orders for insert with check (true);
create policy "public update orders" on public.delivery_orders for update using (true) with check (true);
create policy "public delete orders" on public.delivery_orders for delete using (true);

alter publication supabase_realtime add table public.drivers;
alter publication supabase_realtime add table public.delivery_orders;
